version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    volumes:
      - "./integration-tests:/integration-tests"
      - "./screenshots:/screenshots"
    command: "wait-for-it.sh app:80 -- mocha --recursive /integration-tests"
    links:
      - app
  app:
    image: tutum/hello-world
    expose:
      - "80"
